apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku.service
  labels:
    app: sudoku.service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku.service
  template:
    metadata:
      labels:
        app: sudoku.service
    spec:
      containers:
      - name: sudoku-service
        image: sudoku.service:local
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: sudoku-service
spec:
  selector:
    app: sudoku.service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
