name: Upload to Codecov

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Generate coverage report
        run: ./gradlew clean jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          directory: ./build/reports/jacoco/
